/**
 * StickerPackExporterService.js
 * 
 * 1-Click 16-Pack Sticker Exporter for LINE Creators Market, Discord, & Steam.
 * Features:
 * - 16 Standard Expressive Stickers (370x320 PNG)
 * - LINE Main Cover Image (240x240 PNG)
 * - LINE Store Tab Icon (96x74 PNG)
 * - Steam Points Shop Chat Sticker (150x150 PNG)
 * - Pure-JS Zero-Dependency PKZip binary packer (Store mode with CRC32 verification)
 */

export const PACK_EXPRESSIONS = [
  { id: '01', emotion: 'cheer', caption: { en: 'Good Job!', 'zh-TW': '太棒了！', ja: 'いいね！' } },
  { id: '02', emotion: 'salute', caption: { en: 'Roger That!', 'zh-TW': '遵命！', ja: '了解！' } },
  { id: '03', emotion: 'happy', caption: { en: 'Thank You!', 'zh-TW': '謝謝你！', ja: 'ありがとう！' } },
  { id: '04', emotion: 'shy', caption: { en: 'U-um...', 'zh-TW': '那個……', ja: 'あ、あの…' } },
  { id: '05', emotion: 'cool', caption: { en: 'No Problem', 'zh-TW': '沒問題', ja: '任せて' } },
  { id: '06', emotion: 'sleepy', caption: { en: 'Good Night', 'zh-TW': '晚安囉', ja: 'おやすみ' } },
  { id: '07', emotion: 'thinking', caption: { en: 'Let Me Think', 'zh-TW': '我想想…', ja: 'うーん…' } },
  { id: '08', emotion: 'brave', caption: { en: 'I Got This!', 'zh-TW': '交給我！', ja: '任せろ！' } },
  { id: '09', emotion: 'happy', caption: { en: 'Love You!', 'zh-TW': '超喜歡你！', ja: '大好き！' } },
  { id: '10', emotion: 'thinking', caption: { en: 'What?!', 'zh-TW': '真的假的？！', ja: 'ええっ？！' } },
  { id: '11', emotion: 'shy', caption: { en: 'So Sad...', 'zh-TW': '嗚嗚嗚…', ja: 'しくしく…' } },
  { id: '12', emotion: 'brave', caption: { en: 'Hmph!', 'zh-TW': '哼！生氣了', ja: 'ぷんぷん！' } },
  { id: '13', emotion: 'sleepy', caption: { en: 'Relax Time', 'zh-TW': '休息一下～', ja: '休憩中～' } },
  { id: '14', emotion: 'cheer', caption: { en: 'Keep Going!', 'zh-TW': '繼續加油！', ja: 'ファイト！' } },
  { id: '15', emotion: 'cool', caption: { en: 'Coffee Time', 'zh-TW': '喝杯咖啡吧', ja: 'コーヒータイム' } },
  { id: '16', emotion: 'happy', caption: { en: 'Celebrate!', 'zh-TW': '開派對囉！', ja: 'お祝い！' } }
];

export class StickerPackExporterService {
  constructor(deps = {}) {
    this.synthesizer = deps.stickerSynthesizer || null;
    this.currentSettings = deps.currentSettings || {};
  }

  /**
   * Generates a complete 16-pack ZIP Blob containing all stickers formatted for LINE and Discord.
   * @param {Object} [options]
   * @param {string} [options.style='kawaii']
   * @param {string} [options.language='zh-TW']
   * @param {Function} [options.onProgress] (current, total, status) => void
   * @returns {Promise<{ blob: Blob, filename: string, count: number }>}
   */
  async exportPackZip(options = {}) {
    if (!this.synthesizer) {
      throw new Error('LiveStickerSynthesizerService instance is required for export');
    }

    const style = options.style || 'kawaii';
    const lang = options.language || this.currentSettings?.aiResponseLanguage || 'zh-TW';
    const onProgress = options.onProgress || (() => {});

    const zipFiles = [];
    const totalItems = PACK_EXPRESSIONS.length + 3; // 16 stickers + main + tab + steam
    let completed = 0;

    // 1. Generate 16 Standard Stickers (370 x 320 px)
    for (const item of PACK_EXPRESSIONS) {
      const caption = item.caption[lang] || item.caption.en;
      onProgress(completed, totalItems, `Generating sticker ${item.id} (${caption})...`);

      const dataUrl = await this.synthesizer.generateSticker({
        emotion: item.emotion,
        style: style,
        caption: caption,
        language: lang
      });

      const u8 = this._dataUrlToUint8Array(dataUrl);
      zipFiles.push({ name: `${item.id}.png`, data: u8 });
      completed++;
    }

    // 2. Generate LINE Main Cover Image (240 x 240 px)
    onProgress(completed, totalItems, 'Generating LINE main cover (240x240)...');
    const mainCoverU8 = await this._resizeSticker(zipFiles[0].data, 240, 240);
    zipFiles.push({ name: 'main.png', data: mainCoverU8 });
    completed++;

    // 3. Generate LINE Tab Thumbnail (96 x 74 px)
    onProgress(completed, totalItems, 'Generating LINE tab icon (96x74)...');
    const tabIconU8 = await this._resizeSticker(zipFiles[0].data, 96, 74);
    zipFiles.push({ name: 'tab.png', data: tabIconU8 });
    completed++;

    // 4. Generate Steam Points Shop Chat Sticker (150 x 150 px)
    onProgress(completed, totalItems, 'Generating Steam Chat sticker (150x150)...');
    const steamStickerU8 = await this._resizeSticker(zipFiles[0].data, 150, 150);
    zipFiles.push({ name: 'steam_chat_sticker_150x150.png', data: steamStickerU8 });
    completed++;

    // 5. Add README instructions
    const readmeText = [
      '# LINE & Discord Sticker Pack',
      `Generated by 3D Desktop AI Companion (${style.toUpperCase()} Style)`,
      '',
      '## LINE Creators Market Upload Specs:',
      '- Stickers: 01.png ~ 16.png (370 x 320 px)',
      '- Main Image: main.png (240 x 240 px)',
      '- Tab Icon: tab.png (96 x 74 px)',
      '',
      '## Steam Community Items:',
      '- steam_chat_sticker_150x150.png (150 x 150 px)',
      '',
      '## Discord & Telegram:',
      '- Upload any .png directly as a Custom Sticker or Emoji'
    ].join('\n');

    const encoder = typeof TextEncoder !== 'undefined' ? new TextEncoder() : { encode: (s) => Buffer.from(s) };
    zipFiles.push({ name: 'README.txt', data: new Uint8Array(encoder.encode(readmeText)) });

    onProgress(completed, totalItems, 'Packaging into ZIP archive...');
    const zipBytes = this._createZip(zipFiles);
    const blob = new Blob([zipBytes], { type: 'application/zip' });
    const filename = `sticker-pack-${style}-${Date.now()}.zip`;

    return { blob, filename, count: 16 };
  }

  /**
   * Resizes an image byte array to target dimensions using an offscreen canvas.
   */
  async _resizeSticker(srcBytes, targetWidth, targetHeight) {
    if (typeof document === 'undefined' || !document.createElement) {
      return srcBytes; // In headless tests, return original
    }
    return new Promise((resolve) => {
      const blob = new Blob([srcBytes], { type: 'image/png' });
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = targetWidth;
        canvas.height = targetHeight;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, 0, targetWidth, targetHeight);
          const resizedDataUrl = canvas.toDataURL('image/png');
          resolve(this._dataUrlToUint8Array(resizedDataUrl));
        } else {
          resolve(srcBytes);
        }
      };
      img.onerror = () => resolve(srcBytes);
      img.src = URL.createObjectURL(blob);
    });
  }

  /**
   * Converts Base64 Data URL to Uint8Array.
   */
  _dataUrlToUint8Array(dataUrl) {
    if (!dataUrl || typeof dataUrl !== 'string') return new Uint8Array(0);
    const base64Part = dataUrl.split(',')[1] || dataUrl;
    if (typeof atob === 'function') {
      const binary = atob(base64Part);
      const len = binary.length;
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) {
        bytes[i] = binary.charCodeAt(i);
      }
      return bytes;
    } else if (typeof Buffer !== 'undefined') {
      return new Uint8Array(Buffer.from(base64Part, 'base64'));
    }
    return new Uint8Array(0);
  }

  /**
   * Pure-JS Zero-Dependency PKZip generator (Store mode).
   * Generates a fully specification-compliant .zip file.
   */
  _createZip(files) {
    let localHeaders = [];
    let centralDirectories = [];
    let offset = 0;

    const crcTable = this._getCrcTable();

    for (const file of files) {
      const nameBytes = typeof TextEncoder !== 'undefined'
        ? new TextEncoder().encode(file.name)
        : Buffer.from(file.name);
      const dataBytes = file.data;
      const crc = this._crc32(dataBytes, crcTable);
      const size = dataBytes.length;

      // 1. Local File Header (30 bytes + name length)
      const localHeader = new Uint8Array(30 + nameBytes.length);
      const lView = new DataView(localHeader.buffer);

      lView.setUint32(0, 0x04034b50, true); // Local file header signature
      lView.setUint16(4, 20, true);         // Version needed to extract (2.0)
      lView.setUint16(6, 0, true);          // General purpose bit flag
      lView.setUint16(8, 0, true);          // Compression method (0 = store)
      lView.setUint16(10, 0, true);         // File last mod time
      lView.setUint16(12, 0, true);         // File last mod date
      lView.setUint32(14, crc, true);       // CRC-32
      lView.setUint32(18, size, true);      // Compressed size
      lView.setUint32(22, size, true);      // Uncompressed size
      lView.setUint16(26, nameBytes.length, true); // File name length
      lView.setUint16(28, 0, true);         // Extra field length
      localHeader.set(nameBytes, 30);

      // 2. Central Directory Header (46 bytes + name length)
      const centralDir = new Uint8Array(46 + nameBytes.length);
      const cView = new DataView(centralDir.buffer);

      cView.setUint32(0, 0x02014b50, true); // Central directory signature
      cView.setUint16(4, 20, true);         // Version made by
      cView.setUint16(6, 20, true);         // Version needed to extract
      cView.setUint16(8, 0, true);          // General purpose bit flag
      cView.setUint16(10, 0, true);         // Compression method (store)
      cView.setUint16(12, 0, true);         // Last mod time
      cView.setUint16(14, 0, true);         // Last mod date
      cView.setUint32(16, crc, true);       // CRC-32
      cView.setUint32(20, size, true);      // Compressed size
      cView.setUint32(24, size, true);      // Uncompressed size
      cView.setUint16(28, nameBytes.length, true); // File name length
      cView.setUint16(30, 0, true);         // Extra field length
      cView.setUint16(32, 0, true);         // File comment length
      cView.setUint16(34, 0, true);         // Disk number start
      cView.setUint16(36, 0, true);         // Internal file attributes
      cView.setUint32(38, 0, true);         // External file attributes
      cView.setUint32(42, offset, true);    // Relative offset of local header
      centralDir.set(nameBytes, 46);

      localHeaders.push(localHeader);
      localHeaders.push(dataBytes);
      centralDirectories.push(centralDir);

      offset += localHeader.length + size;
    }

    const centralDirOffset = offset;
    let centralDirSize = 0;
    for (const cd of centralDirectories) {
      centralDirSize += cd.length;
    }

    // 3. End of Central Directory Record (22 bytes)
    const eocd = new Uint8Array(22);
    const eView = new DataView(eocd.buffer);
    eView.setUint32(0, 0x06054b50, true);                  // EOCD signature
    eView.setUint16(4, 0, true);                           // Number of this disk
    eView.setUint16(6, 0, true);                           // Disk where central directory starts
    eView.setUint16(8, files.length, true);                // Number of central directory records on this disk
    eView.setUint16(10, files.length, true);               // Total number of central directory records
    eView.setUint32(12, centralDirSize, true);             // Size of central directory
    eView.setUint32(16, centralDirOffset, true);           // Offset of start of central directory
    eView.setUint16(20, 0, true);                          // Comment length

    // Assemble all bytes
    const totalZipSize = offset + centralDirSize + 22;
    const result = new Uint8Array(totalZipSize);
    let cur = 0;

    for (const part of localHeaders) {
      result.set(part, cur);
      cur += part.length;
    }
    for (const cd of centralDirectories) {
      result.set(cd, cur);
      cur += cd.length;
    }
    result.set(eocd, cur);

    return result;
  }

  _getCrcTable() {
    let c;
    const table = [];
    for (let n = 0; n < 256; n++) {
      c = n;
      for (let k = 0; k < 8; k++) {
        c = ((c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1));
      }
      table[n] = c;
    }
    return table;
  }

  _crc32(bytes, table) {
    let crc = 0 ^ (-1);
    for (let i = 0; i < bytes.length; i++) {
      crc = (crc >>> 8) ^ table[(crc ^ bytes[i]) & 0xFF];
    }
    return (crc ^ (-1)) >>> 0;
  }
}
